### ISSUE TITLE
Spacebar

### ISSUE THREAD

**Issue by r3dh0t** [bsiever/microbit-pxt-blehid#25]
How can you use spacebar? I had a look through the docs but I can't seem to find it.

**Comment by bsiever** [comment]
A space can be typed, so you can send it with the normal `send keys` for the `keyboard` blocks.  Here's an example:  https://makecode.microbit.org/_VLET7h3b60Yt
* "A" Sends just a space
* "B" Sends "B-Space-B". 

I haven't had a chance to check it, but it should be ok.
