### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by amol234545** [bsiever/microbit-pxt-blehid#29]
When I connect the micro:bit to the computer, it recognizes it as a mouse and keyboard but I made the code click and i does not click the mouse.

**Comment by bsiever** [comment]
Can you share a link to the program you were using?

**Comment by amol234545** [comment]
Nevermind, this code works.

**Comment by bsiever** [comment]
@amol234545 Thanks for the update --- I'm glad you got it to work.

**Comment by bsiever** [comment]
@amol234545 Here's a slightly different variation of your code: https://makecode.microbit.org/S39845-80667-84227-07407 . The only important change:  The `bluetooth mouse service` block should only be included once and in the `on start` block.
