### ISSUE TITLE
Typing isssue

### ISSUE THREAD

**Issue by JustablockCode** [bsiever/microbit-pxt-blehid#30]
When i use send keys block, sometimes(very often) it types wrong key or just skips key

**Comment by bsiever** [comment]
@JustablockCode Can you share an example program that has this behavior?  You can use the share feature to create a copy to share: https://makecode.microbit.org/share .

**Comment by JustablockCode** [comment]
> @JustablockCode Can you share an example program that has this behavior? You can use the share feature to create a copy to share: https://makecode.microbit.org/share .

![image](https://github.com/bsiever/microbit-pxt-blehid/assets/132361344/68622256-654b-47f6-8a8f-cd5a2a2b8996)
https://makecode.microbit.org/S54147-92229-30642-68729

**Comment by bsiever** [comment]
@JustablockCode It's possible that the device you're sending keys to can't receive keys at the rate they are being sent. 
1. Can you try this version: https://makecode.microbit.org/S46764-35960-67720-38342 and let me know if it's better?
2. Can you let me know any details about the device you're sending keys to?  (Computer or phone or tablet; model; operating system version)

**Comment by JustablockCode** [comment]
> @JustablockCode It's possible that the device you're sending keys to can't receive keys at the rate they are being sent.
> 
> 1. Can you try this version: https://makecode.microbit.org/S46764-35960-67720-38342 and let me know if it's better?
> 2. Can you let me know any details about the device you're sending keys to?  (Computer or phone or tablet; model; operating system version)

Processor: AMD Ryzen 5 5600H with Radeon Graphics            3.30 GHz
Ram: 8,00 GB
Type: Laptop
OS: WIndows 11 Home
systemtype: x64

**Comment by bsiever** [comment]
@JustablockCode 

Thanks for reporting the error!  I've looked into it and believe I have fixed it.  I've released an updated version of the extension (v0.1.0).

Updates are not used in existing projects by default.  Instructions to update an existing project can be found here: https://kittenbothk-eng.readthedocs.io/en/latest/Makecode/makecode_extensionUpdate.html .  New projects should use the updated version automatically.

I've also added a new block in `keyboard`'s `... more` drawer that provides for better control over the key rate (rate of all events, actually).  If the updated default value still is too fast, you can try to reduce the rate further:
![ChangeRate](https://github.com/bsiever/microbit-pxt-blehid/assets/1421446/a9b9b6dd-40b0-4d1b-8d59-df57429b19dc)

I'm going to "close" this issue, but please re-open it if you notice problems.

**Comment by JustablockCode** [comment]
thx and also what is difference between absolute mouse and mouse

**Comment by bsiever** [comment]
@JustablockCode   Most mice send updates _relative_ to where the mouse is currently located, like "move 5 to the right of where you are".  Absolute Mouse is more like a track pad and uses _absolute_ coordinates, like go to 0,0.  

Mouse is usually better if you're trying to create a device that behaves like a traditional mouse and moves a cursor around the screen.  Absolute Mouse may be better if you're trying to automate something that interacts with the screen, like selecting something from a menu that's known to be at a certain location (Windows menu or the top menu bar on a Mac).
