### ISSUE TITLE
Device name

### ISSUE THREAD

**Issue by microbit-carlos** [bsiever/microbit-pxt-blehid#31]
Hi @bsiever!

First of all, thanks again for such an awesome extension, it's one of my (and many other people) favourites.

I was wondering the reason that the BLE device name was changed to `uBit [xxxxx]`? Just for shortness?

We've noticed that this name is sometimes cached in the OS, and it might still show up before pairing again with a new programme meant to show the DAL/CODAL default name of `BBC micro:bit [xxxxx]`.
We are still running some tests, but what we've seen so far is that in macOS the name is only updated after connecting. So if we have a programme with this extension, connect, and then reflash with a default BLE programme, the `uBit [xxxxx]` name is still shown by macOS until BLE is connected again (after that is finally shows `BBC micro:bit [xxxxx]`).

**Comment by bsiever** [comment]
Hi @microbit-carlos, 

I'd need to review the details, but I believe it was about space in the advertising packet.  I think HID devices needed some additional things in the adv packet, which left less space for the name.  My notes in the source code ([here](https://github.com/bsiever/microbit-pxt-blehid/blob/e05365ea17353fa0ab4e28d232e592212b65783a/HIDService.cpp#L343)) indicate that my advertising packet only has 12 bytes available for the name....which just barely fits the `uBit [xxxxx]` and wouldn't fit `BBC micro:bit...`.

By the way, the Awesome Micro:bit repo is a great resource --- thanks for creating/maintaining it!

**Comment by bsiever** [comment]
Still need to confirm the 12-byte limit.  

It's probably to late/complex to make this change, but if the 12-byte limit is accurate putting the unique part (`[xxxxx]`) first would allow for both approaches with some truncation on the HID.  I.e. `[xxxxx] BBC micro:bit` or `[xxxxx] BBC`.  Or even `[xxxxx] micro:bit` and `[xxxxx] micr`

**Comment by microbit-carlos** [comment]
Thanks for looking into this @bsiever!

As you guessed, unfortunately we are not really able to change the default name at this point, as some mobile apps (and web bluetooth web apps) depend on the name starting with `BBC micro:bit`.
I didn't realised the limitation was with the space left for the name in the advertising packet, that's really interesting, although it means there probably isn't much that can be done.

**Comment by bsiever** [comment]
@microbit-carlos :  iOS used to clear the BLE cached data when you turn Bluetooth off/on.  You may want to see if that works for macOS.  If so, it may be helpful to include in some of micro:bit help/debugging and/or I can add it to my extension's docs.

**Comment by bsiever** [comment]
Closing this issue, but happy to revisit it or update docs if it'll help.
